### ISSUE TITLE
Fields Correct types

### ISSUE THREAD

**Issue by kh-badep** [saidhij/rhfree#2]
those fields should be:
    cin = fields.Char(string="Numéro CIN", required=True)
    matricule_cnss = fields.Char(string="Numéro CNSS", required=True)
    matricule_cimr = fields.Char(string="Numéro CIMR", required=True)
    matricule_mut = fields.Char(string="Numéro MUTUELLE", required=True)

**Comment by saidhij** [comment]
I forgot to change them. Thanks
